# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Worm < Formula
  desc "Wormhole tunnel agent — expose a local port over a shared HTTPS URL"
  homepage "https://github.com/CruGlobal/wormhole"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CruGlobal/worm/releases/download/v0.1.0/worm_0.1.0_darwin_amd64.tar.gz"
      sha256 "7ce5ef600651b21d8d456c0937e19ed1eeed3783fa4264fd5fd768e1bc61ce05"

      define_method(:install) do
        bin.install "worm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CruGlobal/worm/releases/download/v0.1.0/worm_0.1.0_darwin_arm64.tar.gz"
      sha256 "d7ec170930b4d6f95383e4e8a5047377f5175998e016b087c92d6875c7956fd9"

      define_method(:install) do
        bin.install "worm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CruGlobal/worm/releases/download/v0.1.0/worm_0.1.0_linux_amd64.tar.gz"
      sha256 "da5d92c299154e6d09fc0340f8d95c3f6ab279774ae645124330484538959d92"
      define_method(:install) do
        bin.install "worm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CruGlobal/worm/releases/download/v0.1.0/worm_0.1.0_linux_arm64.tar.gz"
      sha256 "b33610e09d5fb65635afed556234bdf9d048b7d17b227da499ebbc888fab0faa"
      define_method(:install) do
        bin.install "worm"
      end
    end
  end

  test do
    assert_match(/\(.*built.*\)/, shell_output("#{bin}/worm version"))
  end
end
