# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Worm < Formula
  desc "Wormhole tunnel agent — expose a local port over a shared HTTPS URL"
  homepage "https://github.com/CruGlobal/wormhole"
  version "0.1.0-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CruGlobal/worm/releases/download/v0.1.0-rc.1/worm_0.1.0-rc.1_darwin_amd64.tar.gz"
      sha256 "ec8fd42c1d76b9934f7878e22d9ac591920cef01cd3596c7d0ed4148ea4355bf"

      define_method(:install) do
        bin.install "worm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CruGlobal/worm/releases/download/v0.1.0-rc.1/worm_0.1.0-rc.1_darwin_arm64.tar.gz"
      sha256 "55c8c6ad3c22cb63599ac044c43686b4e51386e1700a1cf535f4ca642732201d"

      define_method(:install) do
        bin.install "worm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CruGlobal/worm/releases/download/v0.1.0-rc.1/worm_0.1.0-rc.1_linux_amd64.tar.gz"
      sha256 "974ea22bdfeb2062467cc68ab1475b7f067ddbd0e2d6855068da408f42cf0634"
      define_method(:install) do
        bin.install "worm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CruGlobal/worm/releases/download/v0.1.0-rc.1/worm_0.1.0-rc.1_linux_arm64.tar.gz"
      sha256 "775594cf1cbe3096811724104941340e8ea37cfe921b2da9328f06330bc481e6"
      define_method(:install) do
        bin.install "worm"
      end
    end
  end

  test do
    assert_match(/\(.*built.*\)/, shell_output("#{bin}/worm version"))
  end
end
