# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Worm < Formula
  desc "Wormhole tunnel agent — expose a local port over a shared HTTPS URL"
  homepage "https://github.com/CruGlobal/wormhole"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CruGlobal/worm/releases/download/v0.3.0/worm_0.3.0_darwin_amd64.tar.gz"
      sha256 "21899dad951273f5499e2661eead156165b9c488bc0a86a2f512e4f6db7bb2b9"

      define_method(:install) do
        bin.install "worm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CruGlobal/worm/releases/download/v0.3.0/worm_0.3.0_darwin_arm64.tar.gz"
      sha256 "727e864919ba48038e5f637309a5784d96e338d82712db648c935a104325202a"

      define_method(:install) do
        bin.install "worm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CruGlobal/worm/releases/download/v0.3.0/worm_0.3.0_linux_amd64.tar.gz"
      sha256 "dbbf58018c87bd3ea4c7a04ad5035b369883af3ecfbe0d8c5fce8db604115e86"
      define_method(:install) do
        bin.install "worm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CruGlobal/worm/releases/download/v0.3.0/worm_0.3.0_linux_arm64.tar.gz"
      sha256 "fb3c69a3138403092590313ce1d6d2c5e363cc00a804c7dd0d300a6d12dd02e9"
      define_method(:install) do
        bin.install "worm"
      end
    end
  end

  test do
    assert_match(/\(.*built.*\)/, shell_output("#{bin}/worm version"))
  end
end
